site:
  name: Technically Creative LLC
  site: 'https://technicallycreative.work'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null

# Default SEO metadata
metadata:
  title:
    default: Technically Creative
    template: '%s — Technically Creative LLC'
  description: "Process-oriented music technology & project management solutions for creatives and businesses."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Technically Creative LLC
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@technicallycre8' # if you have one, else leave null
    site: '@technicallycre8'
    cardType: summary_large_image
